// Generated by CoffeeScript 1.6.3
(function() {
  helloWorld(function() {
    return prout();
  });

  prout()(function() {
    return console.log("prout");
  });

  helloWorld();

}).call(this);

/*
//@ sourceMappingURL=core.map
*/
